---
title: "Collapse / filtering traits"
author: "Isobel Beasley"
date: "2025-08-21"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    number_sections: true
editor_options: 
  markdown: 
    wrap: 72
---

# Set up 

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE
                      )

library(data.table)
library(dplyr)
library(ggplot2)
library(stringr)

```

## Load data

```{r}

gwas_study_info <- fread(here::here("output/gwas_study_info_cohort_corrected.csv"))

```


# Number of studies per mapped trait


```{r}

# number of studies per mapped trait
n_studies_trait = gwas_study_info |>
  dplyr::group_by(MAPPED_TRAIT, MAPPED_TRAIT_URI) |>
  dplyr::summarise(n_studies = dplyr::n()) |>
  dplyr::arrange(desc(n_studies))

n_studies_trait |>
  head()

n_studies_trait |>
  head() |>
  ggplot(aes(y = reorder(MAPPED_TRAIT, 
                         n_studies), 
             x = n_studies)
         ) + 
  geom_col() + 
  theme_bw() + 
  labs(y = "Trait", x = "Number of studies")

```

# Unmapped / badly mapped traits: 

```{r}
# number of traits only observed once in the catalog 
# likely badly mapped traits: 

n_studies_trait |>
  dplyr::filter(n_studies == 1) |>
  nrow()

unique_mapped_traits = n_studies_trait |>
  dplyr::filter(n_studies == 1) |>
  dplyr::pull(MAPPED_TRAIT)

gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits) |>
  group_by(PUBMED_ID) |>
  summarise(n_unmapped_per_study = n()) |>
  arrange(desc(n_unmapped_per_study)) |>
  head(n = 10)

```
## PUBMED_ID 35870639

```{r}

pubmed_id = 35870639
# this study tests 
# 6,790 proteins or protein complexes
print(paste0("How many studies for pubmed id: ", pubmed_id))
gwas_study_info |>
  filter(PUBMED_ID == pubmed_id) |>
  nrow()

# not all are unmapped 
print(paste0("How many studies for pubmed id: ", pubmed_id, 
        "have unmapped/not well mapped traits"
        )
        )
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  nrow()

not_well_mapped_traits = 
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  pull(MAPPED_TRAIT)

print("Of these unmapped studies, how many contain phrase in blood")
grepl("in blood serum", not_well_mapped_traits) |> sum()
print("level of or amount of")
grepl("level of|amount of", not_well_mapped_traits) |> sum()

# all unmapped 
# map to blood protein amount
# serum proteome - i.e. blood proteome 

gwas_study_info  = 
gwas_study_info |>
  dplyr::rows_update(tibble(PUBMED_ID = pubmed_id, 
                            MAPPED_TRAIT = "blood protein amount",
                            MAPPED_TRAIT_URI = "http://purl.obolibrary.org/obo/OBA_VT0005416"),
                     unmatched = "ignore")


```

## PUBMED_ID: 39789286

```{r}
pubmed_id = 39789286

print(paste0("How many studies for pubmed id: ", pubmed_id))
gwas_study_info |>
  filter(PUBMED_ID == pubmed_id) |>
  nrow()

# not all are unmapped 
print(paste0("How many studies for pubmed id: ", pubmed_id, "have unmapped/not well mapped traits"))
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  nrow()

# 2,821 ratios between protein levels
# i.e. each study is a association study between ratio between two proteins

# ? put under blood protein amount (even though it is a ratio between amounts not an amount...)
gwas_study_info  = 
gwas_study_info |>
  dplyr::rows_update(tibble(PUBMED_ID = pubmed_id, 
                            MAPPED_TRAIT = "blood protein amount",
                            MAPPED_TRAIT_URI = "http://purl.obolibrary.org/obo/OBA_VT0005416"),
                     unmatched = "ignore")

```


## PUBMED_ID: 39789286


```{r}
pubmed_id = 39789286

print(paste0("How many studies for pubmed id: ", pubmed_id))
gwas_study_info |>
  filter(PUBMED_ID == pubmed_id) |>
  nrow()

# not all are unmapped 
print(paste0("How many studies for pubmed id: ", pubmed_id, "have unmapped/not well mapped traits"))
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  nrow()

not_well_mapped_traits = 
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  pull(MAPPED_TRAIT)

print("Of these unmapped studies, how many contain phrase in blood")
grepl("in blood", not_well_mapped_traits) |> sum()
print("level of or amount of")
grepl("level of|amount of", not_well_mapped_traits) |> sum()

print("All unmapped studies are measurements in blood")

gwas_study_info = gwas_study_info |>
  rowwise() |>
  mutate(MAPPED_TRAIT = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                               "blood protein amount",
                               MAPPED_TRAIT)
         ) |>
    mutate(MAPPED_TRAIT_URI = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                                       "http://purl.obolibrary.org/obo/OBA_VT0005416",
                                     MAPPED_TRAIT_URI)
           ) |>
  ungroup()
  
```


## PUBMED_ID: 29875488


```{r}

pubmed_id = 29875488

print(paste0("How many studies for pubmed id: ", pubmed_id))
gwas_study_info |>
  filter(PUBMED_ID == pubmed_id) |>
  nrow()

# not all are unmapped 
print(paste0("How many studies for pubmed id: ", pubmed_id, "have unmapped/not well mapped traits"))
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  nrow()



not_well_mapped_traits = 
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  pull(MAPPED_TRAIT)

print("Of these unmapped studies, how many contain phrase in blood")
grepl("in blood", not_well_mapped_traits) |> sum()
print("level of or amount of")
grepl("level of|amount of|measurement", not_well_mapped_traits) |> sum()

grepl("measurement", not_well_mapped_traits) |> sum()

# study title is: Genomic atlas of the human plasma proteome.

# assume therefore, all these values are protein blood measurements

gwas_study_info = gwas_study_info |>
  rowwise() |>
  mutate(MAPPED_TRAIT = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                               "blood protein amount",
                               MAPPED_TRAIT)
         ) |>
    mutate(MAPPED_TRAIT_URI = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                               "http://purl.obolibrary.org/obo/OBA_VT0005416",
                               MAPPED_TRAIT_URI)
           ) |>
  ungroup()

```

## PUBMED_ID: 39528826

```{r}

# PUBMED_ID: 39528826

# suspect: 
# metabolite measurement	http://www.ebi.ac.uk/efo/EFO_0004725

# Title:
# Publication: Genetic architecture of cerebrospinal fluid and brain metabolite levels and the genetic colocalization of metabolites with human traits.

```


```{r}

# PUBMED+ID: 33634981

# suspect: 
# metabolite measurement	http://www.ebi.ac.uk/efo/EFO_0004725

# Genome-wide association study of metabolites in patients with coronary artery disease identified novel metabolite quantitative trait loci.



```

## PUBMED_ID: 24816252


```{r}

# 24816252

pubmed_id = 24816252

# suspect: 
# metabolite measurement	http://www.ebi.ac.uk/efo/EFO_0004725

# An atlas of genetic influences on human blood metabolites.

print(paste0("How many studies for pubmed id: ", pubmed_id))
gwas_study_info |>
  filter(PUBMED_ID == pubmed_id) |>
  nrow()

# not all are unmapped 
print(paste0("How many studies for pubmed id: ", pubmed_id, "have unmapped/not well mapped traits"))
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  nrow()

not_well_mapped_traits = 
gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits,
                PUBMED_ID == pubmed_id) |>
  pull(MAPPED_TRAIT)

print("Of these unmapped studies, how many contain phrase in blood")
grepl("in blood", not_well_mapped_traits) |> sum()
print("level of or amount of")
grepl("level of|amount of|measurement|ratio", not_well_mapped_traits) |> sum()


gwas_study_info = gwas_study_info |>
  rowwise() |>
  mutate(MAPPED_TRAIT = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                               "blood protein amount",
                               MAPPED_TRAIT)
         ) |>
    mutate(MAPPED_TRAIT_URI = ifelse(PUBMED_ID == pubmed_id && MAPPED_TRAIT %in% unique_mapped_traits,
                               "http://purl.obolibrary.org/obo/OBA_VT0005416",
                               MAPPED_TRAIT_URI)
           ) |>
  ungroup()


```

## PUBMED_ID: 36482414

```{r}

# 36482414
# Publication: Comprehensive characterization of putative genetic influences on plasma metabolome in a pediatric cohort.

```


```{r}

gwas_study_info |>
  dplyr::filter(MAPPED_TRAIT %in% unique_mapped_traits) |>
  group_by(PUBMED_ID, STUDY, COHORT) |>
  summarise(n_unmapped_per_study = n()) |>
  arrange(desc(n_unmapped_per_study))

```


# Saving: 

```{r}

data.table::fwrite(gwas_study_info,
                  here::here("output/gwas_study_info_trait_corrected.csv"), 
                  sep = ",")

```
