---
title: "GWAS Meta-science ideas exploration"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    number_sections: true
editor_options: 
  markdown: 
    wrap: 72
---

<b>
[github repository link](https://github.com/IJbeasley/genomics_ancest_disease_dispar)
</b>

<br>

## Disease burden statistics

-   [Global Burden of Disease Study data - DALYs, deaths etc.](gbd_data_plots.html)

    Global Burden of Disease Study (GBD) global statistics on incidence, prevalence, DALYs (Disability-Adjusted Life Years) and PAF (population Attributable Fraction) for diseases and risk factors.
    
<br>  

## Disease/trait labels 

### Categorize GWAS catalogy traits into disease, response etc.

-   [Download trait ontology information](download_ontology.html)

-   [Categorising GWAS traits into disease, response, measurement etc.](trait_ontology_categorization.html)

### Harmonizing disease trait labels 

-   [Harmonising disease trait labels - typos, synonyms etc.](disease_trait_terms_simplify.html)

-   [Grouping non-cancer disease traits (removing disease subtypes etc) - level 1 grouping](level_1_disease_group_non_cancer.html)

-   [Grouping non-cancer disease traits (removing disease subtypes etc) - level 1 grouping](level_1_disease_group_cancer.html)

-   [Grouping disease traits to match Global Burden of Disease Study Groupings - level 2 grouping](level_2_disease_group.html)


<br>


## Cohort labels 

Allowing us to deal with non-independance between samples.

-   [Fixing & harmonising cohort labels](correcting_cohort_names.html)

    Mostly just correcting for typos and different ways of writing the same cohort name (e.g. Finland vs FINLAND)

-   [Missing cohort information](missing_cohort_info.html) 

-   [Distribution of cohort information exploration](cohort_dist.html)

-   [Looking into: can identify UK Biobank studies from citations?](collapse_cohorts.html)


<br>


## Calculating ancestry biases 

-   [Replicate observed ancestry biases figures in GWAS dataset](replication_ancestry_bias.html)
    
    Replicating Martin et al. 2019 Figure 
    
-  [Disease investigated by ancestry](disease_inves_by_ancest.html)


<br>


## Paper citation metrics

-  [iCite - citation metrics for GWAS Catalog Papers](icite_rcr.html)

    Replicating Reales & Wallace, 2023 - sharing gwas data results in more citations


<br>
<br>

## Archived / not currently being used:

-   [Harmonising trait labels](collapse_traits.html)

